.gitpod.yml
image:
  file: .gitpod.Dockerfile

tasks:
  - name: Setup Maven Project
    init: mvn -q -e -DskipTests install
    command: echo "Environment ready! Run mvn -Dtest=TaskTwoTests test"

vscode:
  extensions:
    - vscjava.vscode-java-pack
    - ritwickdey.LiveServer
    - mhutchie.git-graph

ports:
  - port: 8080
    onOpen: ignore

